#!/bin/sh

# take two numbers from the user
echo "Enter two numbers: "
read a b

# check
if [ $a == $b ]
then
  echo "Numbers are equal."
fi

echo "End of script."
Output:

$ sh if.sh 
Enter two numbers: 
10 20
End of script.

$ sh if.sh 
Enter two numbers: 
10 10
Numbers are equal.
End of script.
